//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestFormApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class FormApp
    {
        public int Title_id { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }
        [DisplayName("Client Priority")]
        public Nullable<int> ClientPriority { get; set; }
        [DisplayName("Target Date")]
        public Nullable<System.DateTime> TargetDate { get; set; }
        [DisplayName("Product Area")]
        public string ProductArea { get; set; }
    }
}
